Demand pandas >= 0.23.0
got following crash
```
  File "/home/adina/Repos/pybids/bids/variables/io.py", line 229, in _load_time_variables
    'regressors', sr)
  File "/home/adina/Repos/pybids/bids/variables/variables.py", line 380, in __init__
    self.index = self._build_entity_index(run_info, sampling_rate)
  File "/home/adina/Repos/pybids/bids/variables/variables.py", line 418, in _build_entity_index
    self.timestamps = pd.concat(_timestamps, axis=0, sort=True)
TypeError: concat() got an unexpected keyword argument 'sort'

```
and according to the https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.concat.html  sort parameter was introduced in pandas 0.23.0

@yarikoptic says Hi