Backport gh-791
Fixup https://github.com/bids-standard/pybids/pull/746

This line seems to have been forgotten when pathlib was introduced. Without this patch, this BIDSLayout is unusable:

```python
    with importlib.resources.path(spinegeneric.config, 'bids_specs.json') as path_sg_layout_config:
        layout = BIDSLayout(data_path,indexer=BIDSLayoutIndexer(config_filename=path_sg_layout_config),validate=False)
```

hits

```
  File ".../site-packages/bids/layout/models.py", line 156, in load
    result = session.query(Config).filter_by(name=config['name']).first()
TypeError: 'PosixPath' object is not subscriptable
```

e.g. https://github.com/spine-generic/data-multi-subject/pull/96/checks#step:13:9

Test BIDSLayout can take custom config_filenames

Test that the entities *defined* by config_filename are respected.

Update bids/layout/tests/test_layout.py

Update bids/layout/tests/test_layout.py

TEST: Pass config to layout, check both str and Path work

FIX: Normalize Paths when storing in databases